name=input("Enter your name:")
usn=input("Enter your USN:")
div=input("Enter your division:")
sub=input("Enter your subject:")
print(f" Student Detils ")
print(f"Name:", name)
print(f"USN:",usn)
print(f"Division:",div)
print(f"Subject:",sub)
